[project]
name = "tabsort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "openai>=2.1.0",
    "pick>=2.4.0",
    "python-dotenv>=1.1.1",
]
